# ==============================================================================
# HYPRLAND CONFIGURATION FILE (MODULAR)
# ==============================================================================

source = conf/monitors.conf
source = conf/programs.conf
source = conf/autostart.conf
source = conf/environments.conf
source = conf/appearance.conf
source = conf/input.conf
source = conf/windowrules.conf
source = conf/keybinds.conf
