# Hyprlock Configuration
# Catppuccin Macchiato Theme

general {
    no_fade_in = false
    grace = 0
    disable_loading = true
}

background {
    monitor =
    path = /home/liskov/.config/hypr/wallpapers/c15.jpeg   # Fondo por defecto
    color = rgba(36, 39, 58, 1.0)
    blur_passes = 2 # 0 disables blurring
    blur_size = 7
    noise = 0.0117
    contrast = 0.8916
    brightness = 0.8172
    vibrancy = 0.1696
    vibrancy_darkness = 0.0
}

# INPUT FIELD
input-field {
    monitor =
    size = 250, 60
    outline_thickness = 2
    dots_size = 0.2 # Scale of input-field height, 0.2 - 0.8
    dots_spacing = 0.2 # Scale of dots' absolute size, 0.0 - 1.0
    dots_center = true
    outer_color = rgba(138, 173, 244, 1.0) # Blue
    inner_color = rgba(54, 58, 79, 1.0)  # Surface0
    font_color = rgba(202, 211, 245, 1.0) # Text
    fade_on_empty = false
    font_family = Hack Nerd Font
    placeholder_text = <span foreground="##cad3f5">Password...</span>
    hide_input = false
    position = 0, -120
    halign = center
    valign = center
}

# TIME
label {
    monitor =
    text = $TIME
    color = rgba(202, 211, 245, 1.0) # Text
    font_size = 120
    font_family = Hack Nerd Font ExtraBold
    position = 0, 80
    halign = center
    valign = center
}

# DATE
label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%A, %d %B")"
    color = rgba(183, 189, 248, 1.0) # Lavender
    font_size = 24
    font_family = Hack Nerd Font
    position = 0, -10
    halign = center
    valign = center
}

# USER
label {
    monitor =
    text = Hello, $USER
    color = rgba(202, 211, 245, 1.0)
    font_size = 18
    font_family = Hack Nerd Font
    position = 0, -70
    halign = center
    valign = center
}
