# ------------------------------------------------------------------------------
# AUTOSTART (Ejecución al inicio)
# ------------------------------------------------------------------------------
# Agente de Polkit para solicitar contraseñas de admin (GUI)
exec-once = /usr/lib/polkit-kde-authentication-agent-1

# Demonio de notificaciones
exec-once = dunst

# Barra de estado
exec-once = waybar

# Demonio de fondos de pantalla y script inicial
exec-once = awww-daemon
exec-once = sleep 1 && ~/.config/hypr/scripts/change_wallpaper.sh

# Inactividad y bloqueo
exec-once = hypridle

# Portapapeles (wl-clipboard y cliphist si se instala)
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
