# ------------------------------------------------------------------------------
# VARIABLES DE ENTORNO (ENV)
# ------------------------------------------------------------------------------
# Tema del cursor
env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24

# Forzar Wayland en aplicaciones
env = QT_QPA_PLATFORM,wayland;xcb
env = GDK_BACKEND,wayland,x11
env = SDL_VIDEODRIVER,wayland
env = CLUTTER_BACKEND,wayland
