# ------------------------------------------------------------------------------
# ENTRADA (Teclado y Ratón)
# ------------------------------------------------------------------------------
input {
    kb_layout = latam # Ajusta el layout de tu teclado (ej. us, latam, es)
    kb_options = grp:alt_shift_toggle # Cambiar entre layouts
    follow_mouse = 1

    touchpad {
        natural_scroll = true
    }

    sensitivity = 0 # -1.0 - 1.0, 0 es sin modificar.
}
