# ------------------------------------------------------------------------------
# MONITORES
# ------------------------------------------------------------------------------
# Configuración por defecto: usar la resolución preferida del monitor conectado.
monitor=,preferred,auto,auto
