# ------------------------------------------------------------------------------
# PROGRAMAS POR DEFECTO
# ------------------------------------------------------------------------------
$terminal = kitty
$fileManager = dolphin
$menu = wofi --show drun
