# ------------------------------------------------------------------------------
# REGLAS DE VENTANAS (Window Rules)
# ------------------------------------------------------------------------------
# Ventanas flotantes por defecto (ejemplo polkit, pavucontrol)
windowrule = float 1, match:class ^(pavucontrol)$
windowrule = float 1, match:class ^(polkit-kde-authentication-agent-1)$

# Opacidad para Kitty
windowrule = opacity 0.85 0.85, match:class ^(kitty)$
